### ISSUE TITLE
1.0 LAUNCH CHECKLIST

### ISSUE THREAD

**Issue by markjrieke** [markjrieke/2024-potus#3]
### Backend

- [x] update to multivariate normal rng in generated quantities
- [x] update to 10,000 iterations (1,250 per chain, 8 chains)
- [x] re-run from 5/1 onwards
- [x] Add all missing function documentation
- [x] Update repository README
- [x] Add sub-dir level READMEs
    - [x] R (add a README with a section for each of the sub-dirs of this folder, i.e., ## data, ## model ...)
    - [x] data 
    - [x] out
    - [x] stan

### Frontend Support

- [x] Finalize text
    - [x] Heading
    - [x] EVS blurb
    - [x] Probability blurb
    - [x] Electoral map blurb
    - [x] Voteshare blurb
    - [x] Similarity blurb
- [x] Formatting
    - [x] Manually set tooltip font in CSS
    - [x] Fix footer (remove attribution for me / D)
    - [x] Add final linebreak
    - [x] Set font color for text (maybe headings?)
    - [x] Adjust manual margin to match `{.column-margin}` formatting
- [x] Functionality
    - [x] update `generate_links()` function to perform internal site linking
    - [x] Add link to model code and output to footer

### Site 

> Tracking in this repository just to keep checklists in one place

- [x] Write *How this works* blog
- [x] National Page
    - [x] Finish qmd body content
    - [x] Add execute param for pulling from main branch
- [x] State Pages
    - [x] Write qmd body content using workable format
    - [x] Add execute params for pulling from main and specifying state
- [x] Site-level support
    - [x] Add rendering script
- [x] Publicize
    - [x] test test test test on dev
    - [x] launch on main
    - [x] draft comms for
        - [x] email
        - [x] linkedin
        - [x] twitter (thread)
        - [x] tr slack wins
        - [x] dsh discord

### Bugs

- [x] Fix issue of missing state-similarity plots on deployed pages with spaces (e.g., New Hampshire, Nebraska CD-1, etc.)
